import os
from uuid import uuid4

from pydub import AudioSegment
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

# folder to save uploaded & processed audio
UPLOAD_DIR = os.path.join(os.path.dirname(__file__), "uploads")
os.makedirs(UPLOAD_DIR, exist_ok=True)

def process_audio_file(file_path: str):
    """
    Process uploaded audio file and return:
    - text: transcription (placeholder)
    - reply: AI reply (placeholder)
    - audio_url: path to processed audio
    """
    try:
        audio = AudioSegment.from_file(file_path)
    except Exception as e:
        raise ValueError(f"Failed to read audio file: {str(e)}")

    # convert uploaded audio to wav for reply
    processed_filename = f"reply_{uuid4().hex}.wav"
    processed_path = os.path.join(UPLOAD_DIR, processed_filename)
    audio.export(processed_path, format="wav")

    # Placeholder text & reply
    text = "Transcribed text goes here"
    reply = "Reply generated by AI goes here"
    audio_url = f"/uploads/{processed_filename}"

    return {"text": text, "reply": reply, "audio_url": audio_url}

# --- FastAPI app ---

app = FastAPI()

# allow frontend at http://localhost:3000
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# serve processed audio
app.mount("/uploads", StaticFiles(directory=UPLOAD_DIR), name="uploads")

@app.post("/api/process-audio")
async def process_audio(file: UploadFile = File(...)):
    tmp_path = os.path.join(UPLOAD_DIR, f"upload_{uuid4().hex}_{file.filename}")
    try:
        # save uploaded file
        with open(tmp_path, "wb") as f:
            f.write(await file.read())

        result = process_audio_file(tmp_path)
        return result
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception:
        raise HTTPException(status_code=500, detail="Internal server error")
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)
